version: "3.9"
services:
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=interviewdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
